import Head from "next/head";
import { FC } from "react";

type Props = {
  title: string;
};

export const Header: FC<Props> = ({ title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
